"on":
    pull_request:
        types:
            - opened
            - edited
            - reopened
            - synchronize
jobs:
    go-tests:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.2.5
                terraform_wrapper: false
            - name: Run terraform Tests
              working-directory: test/unit-test
              run: |
                terraform init
                terraform validate
